### ISSUE TITLE
why fromVC.view.x = 0？

### ISSUE THREAD

**Issue by ForC-M** [TMWu/WeChatFloatBall#1]
FloatTransitionAnimator +replaceAnimation 
fromVC.view.x = 0 这一步为了什么？，并且注释掉动画取消

**Comment by TMWu** [comment]
因为执行缩小动画的UIBezierPath是基于左上角为原点的坐标转换，而且[fromVC.view addSubview:self.coverView];这一行代码，romVC.view添加了一个带透明度的黑色遮罩。
你可以尝试注释掉这行代码看下效果，实际效果会是手势松开之后，缩小成圆球的动画会消失。

**Comment by TMWu** [comment]
因为执行缩小动画的UIBezierPath是基于左上角为原点的坐标转换，而且[fromVC.view addSubview:self.coverView];这一行代码，romVC.view添加了一个带透明度的黑色遮罩。
你可以尝试注释掉这行代码看下效果，实际效果会是手势松开之后，缩小成圆球的动画会消失。
